<a href="https://colab.research.google.com/github/yojulab/with_webscraping/blob/main/codes/APIs/cases/PublicDataReader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PublicDataReader

## 설치하기

In [1]:
!pip install --upgrade PublicDataReader

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting PublicDataReader
  Downloading PublicDataReader-1.0.1-py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 30.8 MB/s
Installing collected packages: PublicDataReader
Successfully installed PublicDataReader-1.0.1

## 국토교통부 실거래가 정보 조회 서비스

In [2]:
# 1. 라이브러리 임포트하기
import PublicDataReader as pdr
print(pdr.__version__)

1.0.1

아래 목록에서 사용할 서비스를 신청 후 이용하시기 바랍니다.

- [국토교통부_아파트매매 실거래 상세 자료](https://www.data.go.kr/data/15057511/openapi.do)  
- [국토교통부_아파트 전월세 자료](https://www.data.go.kr/data/15058017/openapi.do)
- [국토교통부_아파트 분양권전매 신고 자료](https://www.data.go.kr/data/15056782/openapi.do)
- [국토교통부_오피스텔 매매 신고 조회 서비스](https://www.data.go.kr/data/15058452/openapi.do)
- [국토교통부_오피스텔 전월세 신고 조회 서비스](https://www.data.go.kr/data/15059249/openapi.do)
- [국토교통부_연립다세대 매매 실거래자료](https://www.data.go.kr/data/15058038/openapi.do)
- [국토교통부_연립다세대 전월세 자료](https://www.data.go.kr/data/15058016/openapi.do)
- [국토교통부_단독/다가구 매매 실거래 자료](https://www.data.go.kr/data/15058022/openapi.do)
- [국토교통부_단독/다가구 전월세 자료](https://www.data.go.kr/data/15058352/openapi.do)
- [국토교통부_토지 매매 신고 조회 서비스](https://www.data.go.kr/data/15056649/openapi.do)
- [국토교통부_상업업무용 부동산 매매 신고 자료](https://www.data.go.kr/data/15057267/openapi.do)
- [국토교통부_공장 및 창고 등 부동산 매매 신고 자료 조회 서비스](https://www.data.go.kr/data/15100574/openapi.do)
- [국토교통부 건축물대장정보 서비스](https://www.data.go.kr/data/15044713/openapi.do)
- [소상공인 상가업소 정보](https://www.data.go.kr/tcs/dss/selectApiDataDetailView.do?publicDataPk=15012005)
- [서울시 지하철호선별 역별 승하차 인원 정보](http://data.seoul.go.kr/dataList/OA-12914/S/1/datasetView.do)
- [서울시 버스노선별 정류장별 승하차 인원 정보](http://data.seoul.go.kr/dataList/OA-12912/S/1/datasetView.do)

In [33]:
# 2. 공공 데이터 포털 OpenAPI 서비스 인증키 입력하기
serviceKey=""

In [34]:
# 3. 국토교통부 실거래가 정보 조회 OpenAPI 세션 정의하기
# debug: True이면 모든 메시지 출력, False이면 오류 메시지만 출력 (기본값: False)
ts = pdr.Transaction(serviceKey, debug=True)

[INFO] 아파트 매매 조회 서비스 정상 - (00) NORMAL SERVICE.
INFO:root:아파트 매매 조회 서비스 정상 - (00) NORMAL SERVICE.
[ERROR] 아파트 전월세 조회 서비스 오류 - (99) SERVICE ACCESS DENIED ERROR.
ERROR:root:아파트 전월세 조회 서비스 오류 - (99) SERVICE ACCESS DENIED ERROR.
[INFO] 오피스텔 매매 조회 서비스 정상 - (00) NORMAL SERVICE.
INFO:root:오피스텔 매매 조회 서비스 정상 - (00) NORMAL SERVICE.
[ERROR] 오피스텔 전월세 조회 서비스 오류 - (99) SERVICE ACCESS DENIED ERROR.
ERROR:root:오피스텔 전월세 조회 서비스 오류 - (99) SERVICE ACCESS DENIED ERROR.
[INFO] 단독다가구 매매 조회 서비스 정상 - (00) NORMAL SERVICE.
INFO:root:단독다가구 매매 조회 서비스 정상 - (00) NORMAL SERVICE.
[ERROR] 단독다가구 전월세 조회 서비스 오류 - (99) DEADLINE HAS EXPIRED ERROR.
ERROR:root:단독다가구 전월세 조회 서비스 오류 - (99) DEADLINE HAS EXPIRED ERROR.
[INFO] 연립다세대 매매 조회 서비스 정상 - (00) NORMAL SERVICE.
INFO:root:연립다세대 매매 조회 서비스 정상 - (00) NORMAL SERVICE.
[ERROR] 연립다세대 전월세 조회 서비스 오류 - (99) DEADLINE HAS EXPIRED ERROR.
ERROR:root:연립다세대 전월세 조회 서비스 오류 - (99) DEADLINE HAS EXPIRED ERROR.
[INFO] 상업업무용 매매 조회 서비스 정상 - (00) NORMAL SERVICE.
INFO:root:상업업무용 매매 조회 서비스 정상 - (00) NORMAL SERVICE.
[INFO] 토지 매매 조회 서비스 정상 - (00) NORMAL SERVICE.
INFO:root:토지 매매 조회 서비스 정상 - (00) NORMAL SERVICE.
[INFO] 분양입주권 매매 조회 서비스 정상 - (00) NORMAL SERVICE.
INFO:root:분양입주권 매매 조회 서비스 정상 - (00) NORMAL SERVICE.
[ERROR] 공장창고등 매매 조회 서비스 오류 - (99) SERVICE ACCESS DENIED ERROR.
ERROR:root:공장창고등 매매 조회 서비스 오류 - (99) SERVICE ACCESS DENIED ERROR.

In [24]:
# 4. 지역코드(시군구코드) 검색하기
code = pdr.code_bdong()

sigunguName = "부천시"                                  # 시군구코드: 41135
code.loc[(code['시군구명'].str.contains(sigunguName, na=False)) &
         (code['읍면동명'].isna())]
# sigunguName = "소사구"                                  # 시군구코드: 41135
# code.loc[(code['시군구명'].str.contains(sigunguName, na=False))]

     시도코드  시도명  시군구코드     시군구명       법정동코드 읍면동명  동리명      생성일자      말소일자
5241   41  경기도  41190      부천시  4119000000  NaN  NaN  19880423       NaN
5288   41  경기도  41191   부천시 중구  4119100000  NaN  NaN  19880423  19930115
5311   41  경기도  41193   부천시 남구  4119300000  NaN  NaN  19880423  19930115
5328   41  경기도  41195  부천시 원미구  4119500000  NaN  NaN  19930115  20160704
5341   41  경기도  41197  부천시 소사구  4119700000  NaN  NaN  19930115  20160704
5350   41  경기도  41199  부천시 오정구  4119900000  NaN  NaN  19930115  20160704

In [25]:
# 5. 지역, 월 별 데이터 프레임 만들기
prod="아파트"                                           # 부동산 상품 종류 (ex. 아파트, 오피스텔, 단독다가구 등)
trans="매매"                                            # 부동산 거래 유형 (ex. 매매, 전월세)
sigunguCode="41197"
yearMonth="202104"

df = ts.read_data(prod, trans, sigunguCode, yearMonth)
df.head()

Empty DataFrame
Columns: [지역코드, 도로명, 법정동, 지번, 아파트, 건축년도, 층, 전용면적, 년, 월, 일, 거래금액, 도로명건물본번호코드, 도로명건물부번호코드, 도로명시군구코드, 도로명일련번호코드, 도로명지상지하코드, 도로명코드, 법정동본번코드, 법정동부번코드, 법정동시군구코드, 법정동읍면동코드, 법정동지번코드, 일련번호, 거래유형, 중개사소재지, 해제사유발생일, 해제여부]
Index: []

[0 rows x 28 columns]

In [20]:
# 6. 지역, 기간 별 데이터 프레임 만들기
prod="아파트"                                           # 부동산 상품 종류 (ex. 아파트, 오피스텔, 단독다가구 등)
trans="매매"                                            # 부동산 거래 유형 (ex. 매매, 전월세)
# sigunguCode="41135"
startYearMonth="202101"
endYearMonth="202112"

df = ts.collect_data(prod, trans, sigunguCode, startYearMonth, endYearMonth)
df.head()

[INFO] 아파트 매매 202101 조회 시작
INFO:root:아파트 매매 202101 조회 시작
[INFO] 아파트 매매 202102 조회 시작
INFO:root:아파트 매매 202102 조회 시작
[INFO] 아파트 매매 202103 조회 시작
INFO:root:아파트 매매 202103 조회 시작
[INFO] 아파트 매매 202104 조회 시작
INFO:root:아파트 매매 202104 조회 시작
[INFO] 아파트 매매 202105 조회 시작
INFO:root:아파트 매매 202105 조회 시작
[INFO] 아파트 매매 202106 조회 시작
INFO:root:아파트 매매 202106 조회 시작
[INFO] 아파트 매매 202107 조회 시작
INFO:root:아파트 매매 202107 조회 시작
[INFO] 아파트 매매 202108 조회 시작
INFO:root:아파트 매매 202108 조회 시작
[INFO] 아파트 매매 202109 조회 시작
INFO:root:아파트 매매 202109 조회 시작
[INFO] 아파트 매매 202110 조회 시작
INFO:root:아파트 매매 202110 조회 시작
[INFO] 아파트 매매 202111 조회 시작
INFO:root:아파트 매매 202111 조회 시작
[INFO] 아파트 매매 202112 조회 시작
INFO:root:아파트 매매 202112 조회 시작

Empty DataFrame
Columns: [지역코드, 도로명, 법정동, 지번, 아파트, 건축년도, 층, 전용면적, 년, 월, 일, 거래금액, 도로명건물본번호코드, 도로명건물부번호코드, 도로명시군구코드, 도로명일련번호코드, 도로명지상지하코드, 도로명코드, 법정동본번코드, 법정동부번코드, 법정동시군구코드, 법정동읍면동코드, 법정동지번코드, 일련번호, 거래유형, 중개사소재지, 해제사유발생일, 해제여부]
Index: []

[0 rows x 28 columns]